language: node_js
sudo: false
node_js:
- "4"  # nodejs的版本
branches:
  only:
  - hexo
cache:
  directories:
    - node_modules
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
# 解密id_rsa_blog.enc 输出到.ssh/文件夹下，命名为id_rsa
- openssl aes-256-cbc -K $encrypted_1350120bfcc9_key -iv $encrypted_1350120bfcc9_iv
# 设置id_rsa文件权限
- chmod 600 ~/.ssh/id_rsa
# 添加ssh密钥
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
# 添加ssh配置文件
- cp .travis/ssh_config ~/.ssh/config
# 设置github账户信息
- git config user.name "funchs"
- git config user.email "eshore1258@163.com"
install:
- npm install -g hexo-cli
- npm install
# 执行的命令
script:
- npm run deploy
#after_script:
#- cd ./public
#- git init
#- git add .
#- git commit -m "Update docs"
#- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
#env:
#  global:
#  - GH_REF: https://github.com/funchs/funchs.github.io.git

