language: node_js
branches:
  only:
  - hexo
cache:
  directories:
  - node_modules
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'funchs'
- git config --global user.email 'eshore1258@163.com'
- sed -i'' "s~git@github.com:funchs/funchs.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/funchs/funchs.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
env:
  global:
  - secure: ab7Rfsz782N/pjVn10NWFBZgWPRSCgap1hUVOAykanTx9rief1j/C5qs3f9abQUwuGHaQi4w2Y0kyJg/P+Nb6n+hyMrS2Ih+ceGG8o/jHye0sEG34C6YAgQh00hg1Rw4RuKUkpymjnbchDhMWCaJTnlvW+bbAQvpwo4mDNSVZsZSIi6xhHvuLMVgEcgJfWCCdKLKeR0X3PpkVFDcuzZOXQ7b670eKXPmONEjeAdsG4bpiG/zbqxEvaqVRvvPtXi9TGPomOG0tDnUNknBsJzwijEqE+mi8FdM4N1LQ1bRLNSDoquVmT3tfvFXwZb98ORyI/tANp0Poxiw/kFAzvPM3R40J/ZoYAsGzaC48HB2DgwTxQhh2ISg+dHh/4ZvFTqFLN5wlv4/gAN1gBY2fo6zC/DGqCMtgpdR6ySy+fWvZwmGBPY9blf1Ee6oQQ+zta1kOeCsz2FjHc99N8S90w22EboG/5kIG2jZ2AbORQ47c6fCn0n5EHCUVa1Ob3GTZWhovDf0vuihUdNubljTSZAQ6OYJGsU9TGoYWcTBwdU6kZlUF9M8myi8EgZpU6n6CSbWSniEJgfK1rB0JlJfG1OLEcKNdRlxHxFgrl952VA0BEJXxrz2/RxCzbbjNdbNEtN+UKdE0YJ7C8aJg1GVN+yMjZSN2jNW5yUCKiCVWmlIH2Q=
